### ISSUE TITLE
Fix bookmaker_deploy.bats so they can accept html again

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_deploy#27]
Or move to ruby deploy files

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
submitted PR for review here: https://github.com/macmillanpublishers/bookmaker_deploy/pull/29

**Comment by mattretzer** [comment]
https://github.com/macmillanpublishers/bookmaker_deploy/pull/29

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
Deployed! All done!
